delete=Delete
save=Save
email=Email
name=Name
surname=Surname
about=About
gender=Gender
select-gender=Select gender
male=Male
female=Female
other=Other
footer=All rights reserved
lang=My current lang
birthdate=Birthdate
age=Age
password=Password
email-warning=Warning
status=Status
active=Active
inactive=Inactive
page-bad-request=Bad request
page-not-found=Page not found
page-conflict=Conflict