app:
  datasource:
    url: jdbc:postgresql://localhost:5432/charm
    username: charm
    password: charmpass

  content:
    base-path: C:/Users/1saga/apps

  redis:
    host: localhost
    port: 6379