spring:
  application:
    name: charm-back
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8080
  forward-headers-strategy: framework
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
        same-site: lax

app:
  datasource:
    driver-class-name: org.postgresql.Driver
    pool-impl: hikari
    pool-size: 10

  redis:
    port: 6379
    timeout-ms: 2000
    charm-queue-ttl-sec: 300
    charm-empty-ttl-sec: 60
    charm-lock-ttl-sec: 10
    pool:
      max-total: 16
      max-idle: 16
      min-idle: 0
      test-on-borrow: true

logging:
  level:
    root: INFO
    ru.andrewb.charm.back: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO