spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/charm
    username: charm
    password: charmpass
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 8080

app:
  content:
    base-path: C:/Users/1saga/apps
  jwt:
    secret: change-me-change-me-change-me-change-me

logging:
  level:
    root: INFO
    ru.andrewb.charm.back: DEBUG
