spring:
  application:
    name: charm-back
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

server:
  port: 8080

app:
  datasource:
    driver-class-name: org.postgresql.Driver
    pool-impl: hikari
    pool-size: 10

  redis:
    port: 6379
    timeout-ms: 2000
    charm-queue-ttl-sec: 300
    charm-empty-ttl-sec: 60
    charm-lock-ttl-sec: 10
    pool:
      max-total: 16
      max-idle: 16
      min-idle: 0
      test-on-borrow: true
