package ru.andrewb.charm.plugin.linecount.routes;

import ru.andrewb.charm.plugin.linecount.routes.model.RouteEntry;

import java.nio.file.Path;
import java.util.List;

public class RoutesMarkdownRenderer {

    // Creates an output string that will be written to a report file
    public String render(Path path, List<RouteEntry> entries) {
        StringBuilder sb = new StringBuilder();
        sb.append("# Routes\n\n");
        sb.append("Module: ").append(path.getFileName()).append("\n\n");
        sb.append("| Type | Class | Patterns | Source |\n");
        sb.append("|---|---|---|---|\n");

        for (RouteEntry e : entries) {
            sb.append("| ")
                    .append(escapeMd(e.type()))
                    .append(" |")
                    .append(escapeMd(e.clazz()))
                    .append(" |")
                    .append(escapeMd(e.patterns()))
                    .append(" |")
                    .append(escapeMd(e.source().toString()))
                    .append(" |\n");
        }

        sb.append("\nGenerated by linecount:routes\n");
        return sb.toString();
    }

    // Replaces "|" by "\\|" so that it is considered as a text character rather than a Markdown separator
    private static String  escapeMd(String s) {
        return s == null ? "" : s.replace("|", "\\|");
    }
}
